# Generated by Django 2.2.1 on 2019-05-14 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='First Name', max_length=40)),
                ('location', models.CharField(blank=True, help_text='Location', max_length=30)),
                ('joined_date', models.DateTimeField(auto_now=True)),
                ('about', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project name', max_length=255)),
                ('short_description', models.TextField(help_text='Short description')),
                ('location', models.CharField(blank=True, help_text='Location', max_length=30)),
                ('category', models.ForeignKey(blank=True, help_text='Project category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.Category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Person')),
            ],
        ),
    ]
