# Generated by Django 2.2.1 on 2019-06-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
    ]
